schema_version: 1

context:
  name: sim-atlas-toolkit
  version: "0.0.6"
  python_min: '3.11'

package:
  name: sim-atlas-toolkit
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sim-atlas-toolkit//sim_atlas_toolkit-${{ version }}.tar.gz
  sha256: 0548d72e3fb961e7900744b50ff3a05f959674eca3cab72ff6c0b0185c748181

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sim-atlas-upload=sim_atlas_toolkit.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.9.13,<0.10.0
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - pydantic >=2
    - griffe >=2
    - httpx >=0.27
    - pydantic-settings >=2
    - tqdm >=4.68.3


tests:
  - python:
      imports:
        - sim_atlas_toolkit
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - sim-atlas-upload --help

about:
  summary: Tools for parsing and storing workflow nodes with support for pyiron and Python functions
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/XzzX/sim_atlas/

extra:
  recipe-maintainers:
    - niklassiemer
